name: Lint

on: push

jobs:
  lint:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          # added -vX just to reset the cache, feel free to up it if you need
          # to reset the cache again
          cache-name: cache-node-modules-v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: Install npm dependencies
        run: npm install

      - name: Run eslint
        run: npm run lint
